#:import dp kivy.metrics.dp

<HomeScreen>:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "AXNN"
            elevation: 4
            right_action_items: [["greater-than", lambda x: app.go_to_editor()]]

        ScrollView:
            MDBoxLayout:
                orientation: "vertical"
                padding: dp(16)
                spacing: dp(12)
                size_hint_y: None
                height: self.minimum_height

                MDLabel:
                    text: "Catatan Terbaru"
                    font_style: "H6"

                MDBoxLayout:
                    id: recent_notes_container
                    orientation: "vertical"
                    spacing: dp(8)
                    size_hint_y: None
                    height: self.minimum_height

                MDLabel:
                    text: "Tugas Terbaru"
                    font_style: "H6"
                    padding_top: dp(12)

                MDBoxLayout:
                    id: recent_todos_container
                    orientation: "vertical"
                    spacing: dp(8)
                    size_hint_y: None
                    height: self.minimum_height
