#:import dp kivy.metrics.dp

<NotesScreen>:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "Catatan"
            right_action_items: [["plus", lambda x: app.show_add_note()]]

        ScrollView:
            MDBoxLayout:
                id: notes_container
                orientation: "vertical"
                padding: dp(16)
                spacing: dp(8)
                size_hint_y: None
                height: self.minimum_height
