#:import dp kivy.metrics.dp

<SettingsScreen>:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "Pengaturan"

        MDBoxLayout:
            orientation: "vertical"
            padding: dp(16)
            spacing: dp(12)

            MDLabel:
                text: "Pilih Tema"
                font_style: "H6"

            MDRaisedButton:
                text: "☀️ Terang"
                on_release: root.set_theme("light")

            MDRaisedButton:
                text: "🌙 Gelap"
                on_release: root.set_theme("dark")

            MDRaisedButton:
                text: "🟢 Green Matrix"
                on_release: root.set_theme("matrix")
