#:import dp kivy.metrics.dp

<TodosScreen>:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "Daftar Tugas"
            right_action_items: [["plus", lambda x: app.show_add_todo()]]

        ScrollView:
            MDBoxLayout:
                id: todos_container
                orientation: "vertical"
                padding: dp(16)
                spacing: dp(8)
                size_hint_y: None
                height: self.minimum_height
