#:import dp kivy.metrics.dp

<TodoDetailScreen>:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "Detail Tugas"
            left_action_items: [["arrow-left", lambda x: app.go_back()]]

        ScrollView:
            MDBoxLayout:
                orientation: "vertical"
                padding: dp(16)
                spacing: dp(8)
                size_hint_y: None
                height: self.minimum_height

                MDLabel:
                    id: todo_task
                    font_style: "H6" 
